from typing import Dict, List

SUPPORTED_INTENTS: List[str] = [
    "focus_window",
    "new_tab",
    "close_tab",
    "focus_address_bar",
    "quick_open",
    "command_palette",
    "type_text",
    "press_enter",
    "open_app",
    "open_by_index",
    "open_last_project",
    "list_projects",
    "find_file",
    "create_file",
    "summarize_file",
    "save_project",
    "list_windows",
    "active_window",
    "chrome_search",
    "chrome_new_tab",
    "chrome_address_bar",
    "vscode_open_file",
    "vscode_search",
    "vscode_new_file",
    "vscode_quick_open",
    "vscode_command_palette",
    "spotify_play_pause",
    "spotify_next_track",
    "spotify_previous_track",
    "spotify_volume_up",
    "spotify_volume_down",
    "spotify_mute",
]

REQUIRED_FIELDS: Dict[str, List[str]] = {
    "focus_window": ["target"],
    "type_text": ["text"],
    "open_app": ["target"],
    "open_by_index": ["index"],
    "find_file": ["query"],
    "create_file": ["name"],
    "summarize_file": ["path"],
    "save_project": ["path"],
    "chrome_search": ["query"],
    "vscode_open_file": ["filename"],
    "vscode_search": ["query"],
    "vscode_new_file": ["filename"],
}

INTENT_DESCRIPTIONS: Dict[str, str] = {
    "focus_window": "Bring an already open app window to the front.",
    "new_tab": "Open a new browser tab.",
    "close_tab": "Close the current browser tab.",
    "focus_address_bar": "Focus the browser address bar.",
    "quick_open": "Open quick-open search in the active app.",
    "command_palette": "Open the command palette in the active app.",
    "type_text": "Type text into the active focused field.",
    "press_enter": "Press the Enter key.",
    "open_app": "Launch an application.",
    "open_by_index": "Open a ranked search result by numeric index.",
    "open_last_project": "Open the last saved project.",
    "list_projects": "List saved projects.",
    "find_file": "Find a file by query.",
    "create_file": "Create a new file.",
    "summarize_file": "Summarize a file at a given path.",
    "save_project": "Save a project folder path.",
    "list_windows": "List currently open windows.",
    "active_window": "Get the current active window.",
    "chrome_search": "Search a query in Chrome.",
    "chrome_new_tab": "Focus Chrome and open a new tab.",
    "chrome_address_bar": "Focus Chrome and focus its address bar.",
    "vscode_open_file": "Open a file in VS Code.",
    "vscode_search": "Search in VS Code.",
    "vscode_new_file": "Create a new file in VS Code.",
    "vscode_quick_open": "Open VS Code quick open.",
    "vscode_command_palette": "Open VS Code command palette.",
    "spotify_play_pause": "Toggle Spotify play or pause.",
    "spotify_next_track": "Go to the next Spotify track.",
    "spotify_previous_track": "Go to the previous Spotify track.",
    "spotify_volume_up": "Increase system/media volume.",
    "spotify_volume_down": "Decrease system/media volume.",
    "spotify_mute": "Mute or unmute system/media volume.",
}